language: python
python: '2.7'
sudo: false
cache:
  directories:
  - eggs
  - node_modules
  - components
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- rm -rf eggs/plone.app.locales*
- python bootstrap.py -v 1.7.1 -c test-$PLONE_VERSION.cfg
- bin/buildout -N -t 3 -c test-$PLONE_VERSION.cfg annotate
- bin/buildout -N -t 3 -c test-$PLONE_VERSION.cfg
- mkdir -p parts/test/_screenshots
- make install
- node_modules/bower/bin/bower install
- make clean all mode=release
script:
- bin/test $TEST_OPTIONS
- bin/pybot -d parts/test docs
after_script:
- bin/sphinx-build docs html
- gem install --version 0.8.9 faraday
- gem install --version 2.10.0 net-ssh
- gem install travis-artifacts
- travis-artifacts upload --path html
- travis-artifacts upload --path parts/test
- travis-artifacts upload --target-path latest --path html
- travis-artifacts upload --target-path latest --path parts/test
- 'echo "Sphinx: http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/"'
- 'echo "Robot: http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/report.html"'
env:
  matrix:
    - PLONE_VERSION=4.x
    - PLONE_VERSION=5.x
  global:
  - ARTIFACTS_S3_BUCKET=plone-app-mosaic
  - secure: F9djE/1a4VvCidHCnWeF7qkwsUhVLZELv/ttSC1UamsbCCzIa0shUheF4MfAZBRcwtVVAlrid4VRnuYnxyDciy2jrL/qayLfze2ZKcZTfYKsNIrQzyZ4SUVZRB9ZSA6yUK3v+/GIie95as8MKM/UxRtn2RWw4doWGyKv8XBOL4U=
  - secure: buYYreaObmTNEuVTibj/kIyFnIoHCZdezeA8P0HwGHrTbIAwArBFfhG5PC1grT8MayN3f4sfY80d8sRhRATTPNX1smjjBfyni/Zon8OTpr6mGaGsHOg+HHHqocy3hZPlgg1yYLpUCfKCOc8pnq09lF06JwPxsIXAiV+oRHR446E=
irc:
  channels:
  - irc.freenode.org#plone-testing
  template:
  - '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
  - 'Change: %{compare_url}'
  - 'Details: %{build_url}'
  - 'Artifacts: http://plone-app-mosaic.s3-website-us-east-1.amazonaws.com/latest/'
